// JSON schema placeholders and validation constants
export const CADASTRE_STANDARDS = {
  DEFAULT_CRS: 'EPSG:4326',
  LOCAL_METRIC_CRS: 'EPSG:3857',
  MAX_ALLOWED_BOUNDARY_TOLERANCE_METERS: 0.15,
  MAX_ALLOWED_AREA_DISCREPANCY_PERCENT: 1.5,
};
